/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecipeTitleImport } from './routes/recipe/$title'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipeTitleRoute = RecipeTitleImport.update({
  id: '/recipe/$title',
  path: '/recipe/$title',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/recipe/$title': {
      id: '/recipe/$title'
      path: '/recipe/$title'
      fullPath: '/recipe/$title'
      preLoaderRoute: typeof RecipeTitleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipe/$title': typeof RecipeTitleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipe/$title': typeof RecipeTitleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/recipe/$title': typeof RecipeTitleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipe/$title'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipe/$title'
  id: '__root__' | '/' | '/recipe/$title'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipeTitleRoute: typeof RecipeTitleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipeTitleRoute: RecipeTitleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/recipe/$title"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/recipe/$title": {
      "filePath": "recipe/$title.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
